import React, { useEffect, useState } from "react";
import { Separator } from "../ui/separator";
import { Label } from "../ui/label";
import ReactHtmlParser from "html-react-parser";
import { Input } from "../ui/input";
import Chart from "./chart";

type ObjectArray = {
  [key: string]: number;
};

type stepProp = {
  id: number;
  title: string;
  description: string;
  fields: {
    name: string;
    type: string;
    unit: string;
    placeholder: string;
    description: string;
    label: string;
  }[];
};

const dataMatrix: any = {
  PET: {
    Acidification: "5.82E-03",
    "Climate change - Total": "3.02E+00",
    "Climate change - Biogenic": "9.74E-03",
    "Climate change - Fossil": "3.01E+00",
    "Climate change - Land use and LU change": "1.00E-03",
    "Ecotoxicity, freshwater - total": "3.65E+01",
    "Ecotoxicity, freshwater inorganics": "3.59E+01",
    "Ecotoxicity, freshwater organics": "5.22E-01",
    "Eutrophication, freshwater": "2.42E-04",
    "Eutrophication, marine": "1.53E-03",
    "Eutrophication, terrestrial": "1.60E-02",
    "Human toxicity, cancer - Total": "4.89E-09",
    "Human toxicity, cancer - inorganics": "4.47E-09",
    "Human toxicity, cancer - organics": "4.20E-10",
    "Human toxicity, non-cancer -Total": "4.64E-07",
    "Human toxicity, non-cancer - inorganics": "4.63E-07",
    "Human toxicity, non-cancer - organics": "7.47E-10",
    "Ionising radiation - human health": "3.75E-01",
    "Land use": "1.01E+01",
    "Ozone depletion": "7.13E-09",
    "Particulate matter": "3.97E-08",
    "Photochemical ozone formation": "8.19E-03",
    "Resource use, fossils": "8.28E+01",
    "Resource use, minerals and metals": "1.01E-06",
    "Water use": "1.48E+00",
  },
  Trilaminate: {
    Acidification: "7.08E-01",
    "Climate change - Total": "1.51E+02",
    "Climate change - Biogenic": "1.82E-01",
    "Climate change - Fossil": "1.50E+02",
    "Climate change - Land use and LU change": "9.60E-02",
    "Ecotoxicity, freshwater - total": "5.41E+03",
    "Ecotoxicity, freshwater inorganics": "3.55E+03",
    "Ecotoxicity, freshwater organics": "1.86E+03",
    "Eutrophication, freshwater": "3.76E-02",
    "Eutrophication, marine": "1.45E-01",
    "Eutrophication, terrestrial": "1.32E+00",
    "Human toxicity, cancer - Total": "2.67E-07",
    "Human toxicity, cancer - inorganics": "4.97E-08",
    "Human toxicity, cancer - organics": "2.17E-07",
    "Human toxicity, non-cancer -Total": "1.99E-06",
    "Human toxicity, non-cancer - inorganics": "1.24E-06",
    "Human toxicity, non-cancer - organics": "7.47E-07",
    "Ionising radiation - human health": "7.05E+00",
    "Land use": "2.55E+02",
    "Ozone depletion": "1.39E-05",
    "Particulate matter": "7.56E-06",
    "Photochemical ozone formation": "5.62E-01",
    "Resource use, fossils": "3.69E+03",
    "Resource use, minerals and metals": "7.41E-04",
    "Water use": "1.61E+02",
  },
  Truck: {
    Acidification: "3.75E-07",
    "Climate change - Total": "3.22E-04",
    "Climate change - Biogenic": "2.17E-07",
    "Climate change - Fossil": "3.22E-04",
    "Climate change - Land use and LU change": "7.10E-09",
    "Ecotoxicity, freshwater - total": "1.95E-03",
    "Ecotoxicity, freshwater inorganics": "1.92E-03",
    "Ecotoxicity, freshwater organics": "3.24E-05",
    "Eutrophication, freshwater": "6.85E-11",
    "Eutrophication, marine": "1.37E-07",
    "Eutrophication, terrestrial": "1.56E-06",
    "Human toxicity, cancer - Total": "3.70E-14",
    "Human toxicity, cancer - inorganics": "3.54E-14",
    "Human toxicity, cancer - organics": "1.62E-15",
    "Human toxicity, non-cancer -Total": "1.20E-12",
    "Human toxicity, non-cancer - inorganics": "1.19E-12",
    "Human toxicity, non-cancer - organics": "1.90E-14",
    "Ionising radiation - human health": "6.70E-07",
    "Land use": "2.59E-05",
    "Ozone depletion": "4.89E-17",
    "Particulate matter": "2.61E-12",
    "Photochemical ozone formation": "3.49E-07",
    "Resource use, fossils": "4.42E-03",
    "Resource use, minerals and metals": "4.79E-12",
    "Water use": "4.04E-07",
  },
  sea: {
    Acidification: "4.47E-07",
    "Climate change - Total": "2.25E-05",
    "Climate change - Biogenic": "1.98E-08",
    "Climate change - Fossil": "2.24E-05",
    "Climate change - Land use and LU change": "1.18E-08",
    "Ecotoxicity, freshwater - total": "1.42E-04",
    "Ecotoxicity, freshwater inorganics": "1.37E-04",
    "Ecotoxicity, freshwater organics": "4.66E-06",
    "Eutrophication, freshwater": "1.21E-09",
    "Eutrophication, marine": "1.40E-07",
    "Eutrophication, terrestrial": "1.53E-06",
    "Human toxicity, cancer - Total": "1.20E-14",
    "Human toxicity, cancer - inorganics": "7.84E-15",
    "Human toxicity, cancer - organics": "4.20E-15",
    "Human toxicity, non-cancer -Total": "1.11E-13",
    "Human toxicity, non-cancer - inorganics": "1.03E-13",
    "Human toxicity, non-cancer - organics": "8.38E-15",
    "Ionising radiation - human health": "1.73E-07",
    "Land use": "2.26E-05",
    "Ozone depletion": "4.89E-13",
    "Particulate matter": "5.89E-13",
    "Photochemical ozone formation": "4.19E-07",
    "Resource use, fossils": "2.80E-04",
    "Resource use, minerals and metals": "7.23E-11",
    "Water use": "1.16E-06",
  },
  rail: {
    Acidification: "2.08E-07",
    "Climate change - Total": "3.74E-05",
    "Climate change - Biogenic": "1.06E-07",
    "Climate change - Fossil": "3.72E-05",
    "Climate change - Land use and LU change": "8.16E-08",
    "Ecotoxicity, freshwater - total": "2.16E-04",
    "Ecotoxicity, freshwater inorganics": "2.01E-04",
    "Ecotoxicity, freshwater organics": "1.46E-05",
    "Eutrophication, freshwater": "2.20E-08",
    "Eutrophication, marine": "5.23E-08",
    "Eutrophication, terrestrial": "5.25E-07",
    "Human toxicity, cancer - Total": "5.28E-14",
    "Human toxicity, cancer - inorganics": "2.97E-14",
    "Human toxicity, cancer - organics": "2.31E-14",
    "Human toxicity, non-cancer -Total": "4.85E-13",
    "Human toxicity, non-cancer - inorganics": "4.60E-13",
    "Human toxicity, non-cancer - organics": "2.58E-14",
    "Ionising radiation - human health": "1.20E-05",
    "Land use": "4.42E-04",
    "Ozone depletion": "5.66E-13",
    "Particulate matter": "1.75E-12",
    "Photochemical ozone formation": "1.69E-07",
    "Resource use, fossils": "7.06E-04",
    "Resource use, minerals and metals": "1.37E-10",
    "Water use": "1.77E-05",
  },
  air: {
    Acidification: "5.07E-06",
    "Climate change - Total": "1.11E-03",
    "Climate change - Biogenic": "1.31E-07",
    "Climate change - Fossil": "1.11E-03",
    "Climate change - Land use and LU change": "1.13E-07",
    "Ecotoxicity, freshwater - total": "7.08E-03",
    "Ecotoxicity, freshwater inorganics": "6.97E-03",
    "Ecotoxicity, freshwater organics": "1.13E-04",
    "Eutrophication, freshwater": "2.22E-08",
    "Eutrophication, marine": "2.06E-06",
    "Eutrophication, terrestrial": "2.21E-05",
    "Human toxicity, cancer - Total": "1.33E-13",
    "Human toxicity, cancer - inorganics": "9.15E-14",
    "Human toxicity, cancer - organics": "4.19E-14",
    "Human toxicity, non-cancer -Total": "1.18E-11",
    "Human toxicity, non-cancer - inorganics": "1.16E-11",
    "Human toxicity, non-cancer - organics": "2.69E-13",
    "Ionising radiation - human health": "6.72E-06",
    "Land use": "1.11E-03",
    "Ozone depletion": "1.76E-11",
    "Particulate matter": "1.07E-11",
    "Photochemical ozone formation": "7.04E-06",
    "Resource use, fossils": "1.46E-02",
    "Resource use, minerals and metals": "3.44E-10",
    "Water use": "3.93E-05",
  },
  electricTruck: {
    Acidification: "3.28E-07",
    "Climate change - Total": "1.99E-04",
    "Climate change - Biogenic": "3.95E-06",
    "Climate change - Fossil": "1.95E-04",
    "Climate change - Land use and LU change": "1.28E-08",
    "Ecotoxicity, freshwater - total": "2.03E-03",
    "Ecotoxicity, freshwater inorganics": "2.02E-03",
    "Ecotoxicity, freshwater organics": "3.74E-06",
    "Eutrophication, freshwater": "2.82E-10",
    "Eutrophication, marine": "9.26E-08",
    "Eutrophication, terrestrial": "9.90E-07",
    "Human toxicity, cancer - Total": "7.46E-14",
    "Human toxicity, cancer - inorganics": "1.81E-14",
    "Human toxicity, cancer - organics": "5.65E-14",
    "Human toxicity, non-cancer -Total": "2.07E-12",
    "Human toxicity, non-cancer - inorganics": "2.05E-12",
    "Human toxicity, non-cancer - organics": "2.02E-14",
    "Ionising radiation - human health": "4.20E-05",
    "Land use": "2.22E-03",
    "Ozone depletion": "4.67E-15",
    "Particulate matter": "3.04E-12",
    "Photochemical ozone formation": "2.68E-07",
    "Resource use, fossils": "3.89E-03",
    "Resource use, minerals and metals": "4.31E-11",
    "Water use": "1.07E-05",
  },
  dieselTruck: {
    Acidification: "3.75E-07",
    "Climate change - Total": "3.22E-04",
    "Climate change - Biogenic": "2.17E-07",
    "Climate change - Fossil": "3.22E-04",
    "Climate change - Land use and LU change": "7.10E-09",
    "Ecotoxicity, freshwater - total": "1.95E-03",
    "Ecotoxicity, freshwater inorganics": "1.92E-03",
    "Ecotoxicity, freshwater organics": "3.24E-05",
    "Eutrophication, freshwater": "6.85E-11",
    "Eutrophication, marine": "1.37E-07",
    "Eutrophication, terrestrial": "1.56E-06",
    "Human toxicity, cancer - Total": "3.70E-14",
    "Human toxicity, cancer - inorganics": "3.54E-14",
    "Human toxicity, cancer - organics": "1.62E-15",
    "Human toxicity, non-cancer -Total": "1.20E-12",
    "Human toxicity, non-cancer - inorganics": "1.19E-12",
    "Human toxicity, non-cancer - organics": "1.90E-14",
    "Ionising radiation - human health": "6.70E-07",
    "Land use": "2.59E-05",
    "Ozone depletion": "4.89E-17",
    "Particulate matter": "2.61E-12",
    "Photochemical ozone formation": "3.49E-07",
    "Resource use, fossils": "4.42E-03",
    "Resource use, minerals and metals": "4.79E-12",
    "Water use": "4.04E-07",
  },
  electricityGrid: {
    Acidification: "7.50E-04",
    "Climate change - Total": "2.94E-01",
    "Climate change - Biogenic": "1.60E-04",
    "Climate change - Fossil": "2.94E-01",
    "Climate change - Land use and LU change": "3.48E-04",
    "Ecotoxicity, freshwater - total": "4.97E-01",
    "Ecotoxicity, freshwater inorganics": "3.60E-01",
    "Ecotoxicity, freshwater organics": "1.37E-01",
    "Eutrophication, freshwater": "2.91E-05",
    "Eutrophication, marine": "2.09E-04",
    "Eutrophication, terrestrial": "2.37E-03",
    "Human toxicity, cancer - Total": "9.63E-11",
    "Human toxicity, cancer - inorganics": "5.50E-11",
    "Human toxicity, cancer - organics": "4.13E-11",
    "Human toxicity, non-cancer -Total": "1.88E-09",
    "Human toxicity, non-cancer - inorganics": "1.81E-09",
    "Human toxicity, non-cancer - organics": "7.80E-11",
    "Ionising radiation - human health": "2.63E-01",
    "Land use": "3.46E+00",
    "Ozone depletion": "1.50E-08",
    "Particulate matter": "4.40E-09",
    "Photochemical ozone formation": "6.92E-04",
    "Resource use, fossils": "7.91E+00",
    "Resource use, minerals and metals": "7.05E-07",
    "Water use": "5.99E-02",
  },
  electricityLowCarbon: {
    Acidification: "1.54E-04",
    "Climate change - Total": "2.59E-02",
    "Climate change - Biogenic": "3.29E-05",
    "Climate change - Fossil": "2.59E-02",
    "Climate change - Land use and LU change": "3.30E-05",
    "Ecotoxicity, freshwater - total": "2.33E-01",
    "Ecotoxicity, freshwater inorganics": "1.84E-01",
    "Ecotoxicity, freshwater organics": "4.93E-02",
    "Eutrophication, freshwater": "8.70E-06",
    "Eutrophication, marine": "4.70E-05",
    "Eutrophication, terrestrial": "3.42E-04",
    "Human toxicity, cancer - Total": "7.11E-11",
    "Human toxicity, cancer - inorganics": "4.74E-11",
    "Human toxicity, cancer - organics": "2.38E-11",
    "Human toxicity, non-cancer -Total": "8.38E-10",
    "Human toxicity, non-cancer - inorganics": "7.95E-10",
    "Human toxicity, non-cancer - organics": "4.30E-11",
    "Ionising radiation - human health": "2.40E-01",
    "Land use": "7.90E-01",
    "Ozone depletion": "7.03E-10",
    "Particulate matter": "2.09E-09",
    "Photochemical ozone formation": "1.19E-04",
    "Resource use, fossils": "4.74E+00",
    "Resource use, minerals and metals": "6.87E-07",
    "Water use": "5.08E-02",
  },
  naturnalGas: {
    Acidification: "7.83E-05",
    "Climate change - Total": "8.08E-02",
    "Climate change - Biogenic": "1.32E-05",
    "Climate change - Fossil": "8.08E-02",
    "Climate change - Land use and LU change": "1.22E-05",
    "Ecotoxicity, freshwater - total": "5.20E-02",
    "Ecotoxicity, freshwater inorganics": "4.93E-02",
    "Ecotoxicity, freshwater organics": "2.69E-03",
    "Eutrophication, freshwater": "2.62E-06",
    "Eutrophication, marine": "2.39E-05",
    "Eutrophication, terrestrial": "2.57E-04",
    "Human toxicity, cancer - Total": "1.28E-11",
    "Human toxicity, cancer - inorganics": "5.37E-12",
    "Human toxicity, cancer - organics": "7.40E-12",
    "Human toxicity, non-cancer -Total": "1.36E-10",
    "Human toxicity, non-cancer - inorganics": "1.16E-10",
    "Human toxicity, non-cancer - organics": "1.98E-11",
    "Ionising radiation - human health": "5.62E-04",
    "Land use": "2.40E-02",
    "Ozone depletion": "1.64E-09",
    "Particulate matter": "4.55E-10",
    "Photochemical ozone formation": "1.60E-04",
    "Resource use, fossils": "1.21E+00",
    "Resource use, minerals and metals": "3.48E-08",
    "Water use": "2.27E-03",
  },
  waterConsumption: {
    Acidification: "8.86E-03",
    "Climate change - Total": "1.69E+00",
    "Climate change - Biogenic": "7.56E-02",
    "Climate change - Fossil": "1.62E+00",
    "Climate change - Land use and LU change": "2.25E-03",
    "Ecotoxicity, freshwater - total": "4.24E+01",
    "Ecotoxicity, freshwater inorganics": "4.18E+01",
    "Ecotoxicity, freshwater organics": "6.57E-01",
    "Eutrophication, freshwater": "2.26E-03",
    "Eutrophication, marine": "2.02E-02",
    "Eutrophication, terrestrial": "2.08E-02",
    "Human toxicity, cancer - Total": "3.79E-09",
    "Human toxicity, cancer - inorganics": "2.70E-09",
    "Human toxicity, cancer - organics": "1.09E-09",
    "Human toxicity, non-cancer -Total": "1.07E-07",
    "Human toxicity, non-cancer - inorganics": "1.06E-07",
    "Human toxicity, non-cancer - organics": "1.05E-09",
    "Ionising radiation - human health": "1.32E-01",
    "Land use": "4.92E+00",
    "Ozone depletion": "2.43E-07",
    "Particulate matter": "1.05E-07",
    "Photochemical ozone formation": "5.82E-03",
    "Resource use, fossils": "2.30E+01",
    "Resource use, minerals and metals": "7.08E-06",
    "Water use": "-9.56E+01",
  },
  hydrogenPeroxide: {
    Acidification: "3.44E-05",
    "Climate change - Total": "3.95E-03",
    "Climate change - Biogenic": "4.75E-06",
    "Climate change - Fossil": "3.92E-03",
    "Climate change - Land use and LU change": "2.42E-05",
    "Ecotoxicity, freshwater - total": "6.10E-02",
    "Ecotoxicity, freshwater inorganics": "2.96E-02",
    "Ecotoxicity, freshwater organics": "3.14E-02",
    "Eutrophication, freshwater": "1.38E-06",
    "Eutrophication, marine": "8.20E-06",
    "Eutrophication, terrestrial": "7.17E-05",
    "Human toxicity, cancer - Total": "3.89E-12",
    "Human toxicity, cancer - inorganics": "2.44E-12",
    "Human toxicity, cancer - organics": "1.46E-12",
    "Human toxicity, non-cancer -Total": "9.37E-11",
    "Human toxicity, non-cancer - inorganics": "8.73E-11",
    "Human toxicity, non-cancer - organics": "6.38E-12",
    "Ionising radiation - human health": "1.59E-04",
    "Land use": "4.09E-02",
    "Ozone depletion": "2.23E-10",
    "Particulate matter": "3.66E-10",
    "Photochemical ozone formation": "1.44E-05",
    "Resource use, fossils": "4.75E-02",
    "Resource use, minerals and metals": "5.60E-08",
    "Water use": "4.21E-03",
  },
  sodiumHydroxide: {
    Acidification: "3.20E-06",
    "Climate change - Total": "7.37E-04",
    "Climate change - Biogenic": "3.23E-05",
    "Climate change - Fossil": "7.04E-04",
    "Climate change - Land use and LU change": "6.92E-07",
    "Ecotoxicity, freshwater - total": "3.13E-03",
    "Ecotoxicity, freshwater inorganics": "2.96E-03",
    "Ecotoxicity, freshwater organics": "1.69E-04",
    "Eutrophication, freshwater": "1.59E-04",
    "Eutrophication, marine": "6.52E-07",
    "Eutrophication, terrestrial": "6.24E-06",
    "Human toxicity, cancer - Total": "1.68E-12",
    "Human toxicity, cancer - inorganics": "1.47E-12",
    "Human toxicity, cancer - organics": "2.12E-13",
    "Human toxicity, non-cancer -Total": "8.20E-12",
    "Human toxicity, non-cancer - inorganics": "7.71E-12",
    "Human toxicity, non-cancer - organics": "4.93E-13",
    "Ionising radiation - human health": "3.22E-05",
    "Land use": "1.57E-03",
    "Ozone depletion": "1.84E-11",
    "Particulate matter": "4.20E-11",
    "Photochemical ozone formation": "2.45E-06",
    "Resource use, fossils": "1.12E-02",
    "Resource use, minerals and metals": "4.63E-09",
    "Water use": "1.54E-03",
  },
  citricAcid: {
    Acidification: "8.55E-06",
    "Climate change - Total": "1.80E-03",
    "Climate change - Biogenic": "4.26E-06",
    "Climate change - Fossil": "1.33E-03",
    "Climate change - Land use and LU change": "4.67E-04",
    "Ecotoxicity, freshwater - total": "5.04E-02",
    "Ecotoxicity, freshwater inorganics": "7.02E-03",
    "Ecotoxicity, freshwater organics": "4.34E-02",
    "Eutrophication, freshwater": "3.91E-07",
    "Eutrophication, marine": "6.46E-06",
    "Eutrophication, terrestrial": "2.52E-05",
    "Human toxicity, cancer - Total": "3.53E-12",
    "Human toxicity, cancer - inorganics": "6.53E-13",
    "Human toxicity, cancer - organics": "2.88E-12",
    "Human toxicity, non-cancer -Total": "3.77E-11",
    "Human toxicity, non-cancer - inorganics": "2.08E-11",
    "Human toxicity, non-cancer - organics": "1.69E-11",
    "Ionising radiation - human health": "7.66E-05",
    "Land use": "4.94E-02",
    "Ozone depletion": "1.25E-11",
    "Particulate matter": "8.77E-11",
    "Photochemical ozone formation": "8.19E-06",
    "Resource use, fossils": "2.81E-02",
    "Resource use, minerals and metals": "1.16E-08",
    "Water use": "3.68E-03",
  },
  nonIonicDetergent: {
    Acidification: "2.19E-05",
    "Climate change - Total": "4.36E-03",
    "Climate change - Biogenic": "1.77E-05",
    "Climate change - Fossil": "4.34E-03",
    "Climate change - Land use and LU change": "8.92E-06",
    "Ecotoxicity, freshwater - total": "1.53E-02",
    "Ecotoxicity, freshwater inorganics": "1.39E-02",
    "Ecotoxicity, freshwater organics": "1.41E-03",
    "Eutrophication, freshwater": "3.48E-06",
    "Eutrophication, marine": "3.42E-06",
    "Eutrophication, terrestrial": "3.11E-05",
    "Human toxicity, cancer - Total": "2.40E-12",
    "Human toxicity, cancer - inorganics": "1.63E-12",
    "Human toxicity, cancer - organics": "7.78E-13",
    "Human toxicity, non-cancer -Total": "8.87E-11",
    "Human toxicity, non-cancer - inorganics": "8.51E-11",
    "Human toxicity, non-cancer - organics": "3.58E-12",
    "Ionising radiation - human health": "2.24E-03",
    "Land use": "1.67E-02",
    "Ozone depletion": "6.46E-10",
    "Particulate matter": "7.47E-11",
    "Photochemical ozone formation": "1.00E-05",
    "Resource use, fossils": "8.96E-02",
    "Resource use, minerals and metals": "5.99E-08",
    "Water use": "2.76E-03",
  },
  heatPumpGridElectricity: {
    Acidification: "2.19E-05",
    "Climate change - Total": "4.36E-03",
    "Climate change - Biogenic": "1.77E-05",
    "Climate change - Fossil": "4.34E-03",
    "Climate change - Land use and LU change": "8.92E-06",
    "Ecotoxicity, freshwater - total": "1.53E-02",
    "Ecotoxicity, freshwater inorganics": "1.39E-02",
    "Ecotoxicity, freshwater organics": "1.41E-03",
    "Eutrophication, freshwater": "3.48E-06",
    "Eutrophication, marine": "3.42E-06",
    "Eutrophication, terrestrial": "3.11E-05",
    "Human toxicity, cancer - Total": "2.40E-12",
    "Human toxicity, cancer - inorganics": "1.63E-12",
    "Human toxicity, cancer - organics": "7.78E-13",
    "Human toxicity, non-cancer -Total": "8.87E-11",
    "Human toxicity, non-cancer - inorganics": "8.51E-11",
    "Human toxicity, non-cancer - organics": "3.58E-12",
    "Ionising radiation - human health": "2.24E-03",
    "Land use": "1.67E-02",
    "Ozone depletion": "6.46E-10",
    "Particulate matter": "7.47E-11",
    "Photochemical ozone formation": "1.00E-05",
    "Resource use, fossils": "8.96E-02",
    "Resource use, minerals and metals": "5.99E-08",
    "Water use": "2.76E-03",
  },
  heatPumpLowCarbonElectricity: {
    Acidification: "4.25E-06",
    "Climate change - Total": "7.14E-04",
    "Climate change - Biogenic": "9.07E-07",
    "Climate change - Fossil": "7.12E-04",
    "Climate change - Land use and LU change": "9.09E-07",
    "Ecotoxicity, freshwater - total": "6.42E-03",
    "Ecotoxicity, freshwater inorganics": "5.06E-03",
    "Ecotoxicity, freshwater organics": "1.36E-03",
    "Eutrophication, freshwater": "2.40E-07",
    "Eutrophication, marine": "1.30E-06",
    "Eutrophication, terrestrial": "9.43E-06",
    "Human toxicity, cancer - Total": "1.96E-12",
    "Human toxicity, cancer - inorganics": "1.31E-12",
    "Human toxicity, cancer - organics": "6.55E-13",
    "Human toxicity, non-cancer -Total": "2.31E-11",
    "Human toxicity, non-cancer - inorganics": "2.19E-11",
    "Human toxicity, non-cancer - organics": "1.19E-12",
    "Ionising radiation - human health": "6.62E-03",
    "Land use": "2.18E-02",
    "Ozone depletion": "1.94E-11",
    "Particulate matter": "5.75E-11",
    "Photochemical ozone formation": "3.28E-06",
    "Resource use, fossils": "1.30E-01",
    "Resource use, minerals and metals": "1.89E-08",
    "Water use": "1.40E-03",
  },
  electricalDryerGridElectricity: {
    Acidification: "1.54E-04",
    "Climate change - Total": "2.59E-02",
    "Climate change - Biogenic": "3.29E-05",
    "Climate change - Fossil": "2.59E-02",
    "Climate change - Land use and LU change": "3.30E-05",
    "Ecotoxicity, freshwater - total": "2.33E-01",
    "Ecotoxicity, freshwater inorganics": "1.84E-01",
    "Ecotoxicity, freshwater organics": "4.93E-02",
    "Eutrophication, freshwater": "8.70E-06",
    "Eutrophication, marine": "4.70E-05",
    "Eutrophication, terrestrial": "3.42E-04",
    "Human toxicity, cancer - Total": "7.11E-11",
    "Human toxicity, cancer - inorganics": "4.74E-11",
    "Human toxicity, cancer - organics": "2.38E-11",
    "Human toxicity, non-cancer -Total": "8.38E-10",
    "Human toxicity, non-cancer - inorganics": "7.95E-10",
    "Human toxicity, non-cancer - organics": "4.30E-11",
    "Ionising radiation - human health": "2.40E-01",
    "Land use": "7.90E-01",
    "Ozone depletion": "7.03E-10",
    "Particulate matter": "2.09E-09",
    "Photochemical ozone formation": "1.19E-04",
    "Resource use, fossils": "4.74E+00",
    "Resource use, minerals and metals": "6.87E-07",
    "Water use": "5.08E-02",
  },
  electricalDryerLowCarbonElectricity: {
    Acidification: "8.35E-04",
    "Climate change - Total": "3.04E-01",
    "Climate change - Biogenic": "7.67E-05",
    "Climate change - Fossil": "3.04E-01",
    "Climate change - Land use and LU change": "5.01E-05",
    "Ecotoxicity, freshwater - total": "6.69E-01",
    "Ecotoxicity, freshwater inorganics": "6.52E-01",
    "Ecotoxicity, freshwater organics": "1.64E-02",
    "Eutrophication, freshwater": "3.41E-05",
    "Eutrophication, marine": "1.39E-04",
    "Eutrophication, terrestrial": "1.43E-03",
    "Human toxicity, cancer - Total": "7.86E-11",
    "Human toxicity, cancer - inorganics": "2.84E-11",
    "Human toxicity, cancer - organics": "5.01E-11",
    "Human toxicity, non-cancer -Total": "1.08E-09",
    "Human toxicity, non-cancer - inorganics": "1.00E-09",
    "Human toxicity, non-cancer - organics": "7.26E-11",
    "Ionising radiation - human health": "7.45E-03",
    "Land use": "2.86E-01",
    "Ozone depletion": "9.57E-09",
    "Particulate matter": "8.08E-09",
    "Photochemical ozone formation": "7.06E-04",
    "Resource use, fossils": "4.34E+00",
    "Resource use, minerals and metals": "9.83E-08",
    "Water use": "1.65E-02",
  },
  repurposingPET: {
    Acidification: "-1.16E-03",
    "Climate change - Total": "-6.40E-02",
    "Climate change - Biogenic": "-8.00E-05",
    "Climate change - Fossil": "-6.39E-02",
    "Climate change - Land use and LU change": "-4.04E-05",
    "Ecotoxicity, freshwater - total": "-2.27E+00",
    "Ecotoxicity, freshwater inorganics": "-1.50E+00",
    "Ecotoxicity, freshwater organics": "-7.75E-01",
    "Eutrophication, freshwater": "-1.58E-05",
    "Eutrophication, marine": "-6.11E-05",
    "Eutrophication, terrestrial": "-5.57E-04",
    "Human toxicity, cancer - Total": "-1.13E-10",
    "Human toxicity, cancer - inorganics": "-2.26E-11",
    "Human toxicity, cancer - organics": "-9.05E-11",
    "Human toxicity, non-cancer -Total": "-1.02E-09",
    "Human toxicity, non-cancer - inorganics": "-7.10E-10",
    "Human toxicity, non-cancer - organics": "-3.12E-10",
    "Ionising radiation - human health": "-3.09E-03",
    "Land use": "-1.10E-01",
    "Ozone depletion": "-5.80E-09",
    "Particulate matter": "-3.17E-09",
    "Photochemical ozone formation": "-2.38E-04",
    "Resource use, fossils": "-1.57E+00",
    "Resource use, minerals and metals": "-3.09E-07",
    "Water use": "-6.75E-02",
  },
  repurposingTrilaminate: {
    Acidification: "-1.42E-01",
    "Climate change - Total": "-3.01E+01",
    "Climate change - Biogenic": "-3.65E-02",
    "Climate change - Fossil": "-3.01E+01",
    "Climate change - Land use and LU change": "-1.92E-02",
    "Ecotoxicity, freshwater - total": "-1.08E+03",
    "Ecotoxicity, freshwater inorganics": "-7.11E+02",
    "Ecotoxicity, freshwater organics": "-3.72E+02",
    "Eutrophication, freshwater": "-7.53E-03",
    "Eutrophication, marine": "-2.90E-02",
    "Eutrophication, terrestrial": "-2.64E-01",
    "Human toxicity, cancer - Total": "-5.33E-08",
    "Human toxicity, cancer - inorganics": "-9.94E-09",
    "Human toxicity, cancer - organics": "-4.34E-08",
    "Human toxicity, non-cancer -Total": "-3.98E-07",
    "Human toxicity, non-cancer - inorganics": "-2.48E-07",
    "Human toxicity, non-cancer - organics": "-1.49E-07",
    "Ionising radiation - human health": "-1.41E+00",
    "Land use": "-5.09E+01",
    "Ozone depletion": "-2.78E-06",
    "Particulate matter": "-1.51E-06",
    "Photochemical ozone formation": "-1.12E-01",
    "Resource use, fossils": "-7.39E+02",
    "Resource use, minerals and metals": "-1.48E-04",
    "Water use": "-3.21E+01",
  },
  incinerationPETWithoutEnergyRecovery: {
    Acidification: "4.58E-04",
    "Climate change - Total": "2.03E+00",
    "Climate change - Biogenic": "7.19E-06",
    "Climate change - Fossil": "2.03E+00",
    "Climate change - Land use and LU change": "4.61E-06",
    "Ecotoxicity, freshwater - total": "1.05E+00",
    "Ecotoxicity, freshwater inorganics": "1.05E+00",
    "Ecotoxicity, freshwater organics": "2.26E-03",
    "Eutrophication, freshwater": "2.29E-06",
    "Eutrophication, marine": "2.84E-04",
    "Eutrophication, terrestrial": "2.48E-03",
    "Human toxicity, cancer - Total": "3.38E-10",
    "Human toxicity, cancer - inorganics": "5.92E-11",
    "Human toxicity, cancer - organics": "2.79E-10",
    "Human toxicity, non-cancer -Total": "4.20E-09",
    "Human toxicity, non-cancer - inorganics": "4.19E-09",
    "Human toxicity, non-cancer - organics": "9.79E-12",
    "Ionising radiation - human health": "3.90E-04",
    "Land use": "3.61E-02",
    "Ozone depletion": "8.68E-10",
    "Particulate matter": "2.84E-09",
    "Photochemical ozone formation": "6.32E-04",
    "Resource use, fossils": "1.39E-01",
    "Resource use, minerals and metals": "3.22E-08",
    "Water use": "2.22E-02",
  },
  incinerationPETWithEnergyRecovery: {
    Acidification: "-7.20E-04",
    "Climate change - Total": "1.26E+00",
    "Climate change - Biogenic": "-2.23E-04",
    "Climate change - Fossil": "1.26E+00",
    "Climate change - Land use and LU change": "-3.96E-04",
    "Ecotoxicity, freshwater - total": "2.68E-01",
    "Ecotoxicity, freshwater inorganics": "4.11E-01",
    "Ecotoxicity, freshwater organics": "-1.42E-01",
    "Eutrophication, freshwater": "-4.08E-05",
    "Eutrophication, marine": "-5.61E-05",
    "Eutrophication, terrestrial": "-1.29E-03",
    "Human toxicity, cancer - Total": "1.70E-10",
    "Human toxicity, cancer - inorganics": "-2.49E-11",
    "Human toxicity, cancer - organics": "1.95E-10",
    "Human toxicity, non-cancer -Total": "1.61E-09",
    "Human toxicity, non-cancer - inorganics": "1.79E-09",
    "Human toxicity, non-cancer - organics": "-1.83E-10",
    "Ionising radiation - human health": "-2.50E-01",
    "Land use": "-3.35E+00",
    "Ozone depletion": "-2.32E-08",
    "Particulate matter": "-4.05E-09",
    "Photochemical ozone formation": "-9.84E-04",
    "Resource use, fossils": "-1.46E+01",
    "Resource use, minerals and metals": "-8.39E-07",
    "Water use": "-4.77E-02",
  },
  incinerationTrilaminateWithoutEnergyRecovery: {
    Acidification: "1.08E-03",
    "Climate change - Total": "2.34E+00",
    "Climate change - Biogenic": "1.62E-04",
    "Climate change - Fossil": "2.34E+00",
    "Climate change - Land use and LU change": "2.73E-05",
    "Ecotoxicity, freshwater - total": "2.41E+00",
    "Ecotoxicity, freshwater inorganics": "2.40E+00",
    "Ecotoxicity, freshwater organics": "5.24E-03",
    "Eutrophication, freshwater": "5.06E-06",
    "Eutrophication, marine": "6.14E-04",
    "Eutrophication, terrestrial": "5.45E-03",
    "Human toxicity, cancer - Total": "1.59E-10",
    "Human toxicity, cancer - inorganics": "6.61E-11",
    "Human toxicity, cancer - organics": "9.30E-11",
    "Human toxicity, non-cancer -Total": "1.80E-09",
    "Human toxicity, non-cancer - inorganics": "1.78E-09",
    "Human toxicity, non-cancer - organics": "2.07E-11",
    "Ionising radiation - human health": "3.08E-03",
    "Land use": "1.72E-01",
    "Ozone depletion": "5.41E-09",
    "Particulate matter": "4.95E-09",
    "Photochemical ozone formation": "1.12E-03",
    "Resource use, fossils": "6.74E-01",
    "Resource use, minerals and metals": "1.02E-07",
    "Water use": "1.85E-01",
  },
  incinerationTrilaminateWithEnergyRecovery: {
    Acidification: "-1.58E-04",
    "Climate change - Total": "1.53E+00",
    "Climate change - Biogenic": "-7.99E-05",
    "Climate change - Fossil": "1.53E+00",
    "Climate change - Land use and LU change": "-3.94E-04",
    "Ecotoxicity, freshwater - total": "1.59E+00",
    "Ecotoxicity, freshwater inorganics": "1.73E+00",
    "Ecotoxicity, freshwater organics": "-1.47E-01",
    "Eutrophication, freshwater": "-4.03E-05",
    "Eutrophication, marine": "2.56E-04",
    "Eutrophication, terrestrial": "1.47E-03",
    "Human toxicity, cancer - Total": "-1.74E-11",
    "Human toxicity, cancer - inorganics": "-2.24E-11",
    "Human toxicity, cancer - organics": "5.02E-12",
    "Human toxicity, non-cancer -Total": "-9.30E-10",
    "Human toxicity, non-cancer - inorganics": "-7.47E-10",
    "Human toxicity, non-cancer - organics": "-1.83E-10",
    "Ionising radiation - human health": "-2.60E-01",
    "Land use": "-3.39E+00",
    "Ozone depletion": "-1.99E-08",
    "Particulate matter": "-2.30E-09",
    "Photochemical ozone formation": "-5.84E-04",
    "Resource use, fossils": "-1.48E+01",
    "Resource use, minerals and metals": "-8.16E-07",
    "Water use": "1.11E-01",
  },
  landfillPET: {
    Acidification: "8.59E-05",
    "Climate change - Total": "1.28E-01",
    "Climate change - Biogenic": "6.40E-05",
    "Climate change - Fossil": "1.27E-01",
    "Climate change - Land use and LU change": "9.07E-06",
    "Ecotoxicity, freshwater - total": "1.85E-01",
    "Ecotoxicity, freshwater inorganics": "1.78E-01",
    "Ecotoxicity, freshwater organics": "6.79E-03",
    "Eutrophication, freshwater": "1.60E-06",
    "Eutrophication, marine": "4.80E-04",
    "Eutrophication, terrestrial": "3.38E-04",
    "Human toxicity, cancer - Total": "8.73E-12",
    "Human toxicity, cancer - inorganics": "5.21E-12",
    "Human toxicity, cancer - organics": "3.52E-12",
    "Human toxicity, non-cancer -Total": "2.62E-10",
    "Human toxicity, non-cancer - inorganics": "9.93E-11",
    "Human toxicity, non-cancer - organics": "1.63E-10",
    "Ionising radiation - human health": "3.59E-04",
    "Land use": "5.80E-01",
    "Ozone depletion": "2.78E-10",
    "Particulate matter": "1.77E-09",
    "Photochemical ozone formation": "1.46E-04",
    "Resource use, fossils": "2.63E-01",
    "Resource use, minerals and metals": "2.50E-08",
    "Water use": "1.13E-02",
  },
  landfillTrilaminate: {
    Acidification: "1.83E-04",
    "Climate change - Total": "8.01E-02",
    "Climate change - Biogenic": "1.16E-04",
    "Climate change - Fossil": "8.00E-02",
    "Climate change - Land use and LU change": "4.59E-05",
    "Ecotoxicity, freshwater - total": "1.26E+00",
    "Ecotoxicity, freshwater inorganics": "8.52E-01",
    "Ecotoxicity, freshwater organics": "4.10E-01",
    "Eutrophication, freshwater": "1.06E-05",
    "Eutrophication, marine": "6.14E-03",
    "Eutrophication, terrestrial": "5.03E-04",
    "Human toxicity, cancer - Total": "3.51E-11",
    "Human toxicity, cancer - inorganics": "3.11E-11",
    "Human toxicity, cancer - organics": "4.01E-12",
    "Human toxicity, non-cancer -Total": "2.65E-09",
    "Human toxicity, non-cancer - inorganics": "2.55E-09",
    "Human toxicity, non-cancer - organics": "9.87E-11",
    "Ionising radiation - human health": "1.59E-03",
    "Land use": "2.35E-01",
    "Ozone depletion": "9.11E-11",
    "Particulate matter": "2.01E-09",
    "Photochemical ozone formation": "1.55E-04",
    "Resource use, fossils": "8.29E-01",
    "Resource use, minerals and metals": "1.68E-08",
    "Water use": "3.05E-03",
  },
};

function Calculator({ step, steps }: { step: number; steps: stepProp[] }) {
  const [formState, setFormState] = useState<ObjectArray>({
    PET: 0,
    Trilaminate: 0,
    Truck: 0,
    sea: 0,
    rail: 0,
    air: 0,
    temp: 0,
    load: 0,
    wash_time: 0,
    electricityGrid: 0,
    electricityLowCarbon: 0,
    naturnalGas: 0,
    waterConsumption: 0,
    sodiumHydroxide: 0,
    hydrogenPeroxide: 0,
    citricAcid: 0,
    nonIonicDetergent: 0,
    heatPumpGridElectricity: 0,
    heatPumpLowCarbonElectricity: 0,
    electricalDryerGridElectricity: 0,
    electricalDryerLowCarbonElectricity: 0,
    dieselTruck: 0,
    electricTruck: 0,
    numUses: 0,
    repurposing: 0,
    incinerationEnergyRecovery: 0,
    IncinerationWithoutEnergyRecovery: 0,
    Landfill: 0,
  });
  const [currentChartState, setCurrentChartState] = useState({
    "Materials manufacturing": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "Transportation to RZ centre": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "Washing-Electricity/Natural gas consumption": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "Washing-Water consumption": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    Drying: {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "Transportation to the consumer": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "Washing-Detergent": {
      Acidification: 0,
      "Climate change - Total": 0,
      "Climate change - Biogenic": 0,
      "Climate change - Fossil": 0,
      "Climate change - Land use and LU change": 0,
      "Ecotoxicity, freshwater - total": 0,
      "Ecotoxicity, freshwater inorganics": 0,
      "Ecotoxicity, freshwater organics": 0,
      "Eutrophication, freshwater": 0,
      "Eutrophication, marine": 0,
      "Eutrophication, terrestrial": 0,
      "Human toxicity, cancer - Total": 0,
      "Human toxicity, cancer - inorganics": 0,
      "Human toxicity, cancer - organics": 0,
      "Human toxicity, non-cancer -Total": 0,
      "Human toxicity, non-cancer - inorganics": 0,
      "Human toxicity, non-cancer - organics": 0,
      "Ionising radiation - human health": 0,
      "Land use": 0,
      "Ozone depletion": 0,
      "Particulate matter": 0,
      "Photochemical ozone formation": 0,
      "Resource use, fossils": 0,
      "Resource use, minerals and metals": 0,
      "Water use": 0,
    },
    "End-of-life": {
      Acidification: null,
      "Climate change - Total": null,
      "Climate change - Biogenic": null,
      "Climate change - Fossil": null,
      "Climate change - Land use and LU change": null,
      "Ecotoxicity, freshwater - total": null,
      "Ecotoxicity, freshwater inorganics": null,
      "Ecotoxicity, freshwater organics": null,
      "Eutrophication, freshwater": null,
      "Eutrophication, marine": null,
      "Eutrophication, terrestrial": null,
      "Human toxicity, cancer - Total": null,
      "Human toxicity, cancer - inorganics": null,
      "Human toxicity, cancer - organics": null,
      "Human toxicity, non-cancer -Total": null,
      "Human toxicity, non-cancer - inorganics": null,
      "Human toxicity, non-cancer - organics": null,
      "Ionising radiation - human health": null,
      "Land use": null,
      "Ozone depletion": null,
      "Particulate matter": null,
      "Photochemical ozone formation": null,
      "Resource use, fossils": null,
      "Resource use, minerals and metals": null,
      "Water use": null,
    },
  });

  useEffect(() => {
    const result: any = {};
    result["Materials manufacturing"] = {};
    result["Transportation to RZ centre"] = {};
    result["Washing-Electricity/Natural gas consumption"] = {};
    result["Washing-Water consumption"] = {};
    result["Drying"] = {};
    result["Transportation to the consumer"] = {};
    result["Washing-Detergent"] = {};
    result["End-of-life"] = {};

    Object.keys(dataMatrix["repurposingPET"]).forEach((key) => {
      ["PET", "Trilaminate"].forEach((v, i) => {
        if (i == 0) {
          result["Materials manufacturing"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        } else
          result["Materials manufacturing"][key] +=
            Number(dataMatrix[v][key]) * Number(formState[v]);
      });

      ["Truck", "sea", "rail", "air"].forEach((v, i) => {
        if (i == 0) {
          result["Transportation to RZ centre"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        } else
          result["Transportation to RZ centre"][key] +=
            Number(dataMatrix[v][key]) * Number(formState[v]);
      });

      // step 3
      [
        "electricityGrid",
        "electricityLowCarbon",
        "naturnalGas",
        "waterConsumption",
      ].forEach((v, i) => {
        if (v !== "waterConsumption") {
          if (i == 0) {
            result["Washing-Electricity/Natural gas consumption"][key] =
              Number(dataMatrix[v][key]) * Number(formState[v]);
          } else
            result["Washing-Electricity/Natural gas consumption"][key] +=
              Number(dataMatrix[v][key]) * Number(formState[v]);
        } else {
          result["Washing-Water consumption"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        }
      });

      [
        "sodiumHydroxide",
        "hydrogenPeroxide",
        "citricAcid",
        "nonIonicDetergent",
      ].forEach((v, i) => {
        if (i == 0) {
          result["Washing-Detergent"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        } else
          result["Washing-Detergent"][key] +=
            Number(dataMatrix[v][key]) * Number(formState[v]);
      });

      [
        "heatPumpGridElectricity",
        "heatPumpLowCarbonElectricity",
        "electricalDryerGridElectricity",
        "electricalDryerLowCarbonElectricity",
      ].forEach((v, i) => {
        if (i == 0) {
          result["Drying"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        } else
          result["Drying"][key] +=
            Number(dataMatrix[v][key]) * Number(formState[v]);
      });

      ["dieselTruck", "electricTruck"].forEach((v, i) => {
        if (i == 0) {
          result["Transportation to the consumer"][key] =
            Number(dataMatrix[v][key]) * Number(formState[v]);
        } else
          result["Transportation to the consumer"][key] +=
            Number(dataMatrix[v][key]) * Number(formState[v]);
      });

      result["End-of-life"][key] =
        (Number(formState["repurposing"]) / 100) *
        (Number(formState["PET"]) * Number(dataMatrix["repurposingPET"][key]) +
          Number(formState["Trilaminate"]) *
            Number(dataMatrix["repurposingTrilaminate"][key]));

      result["End-of-life"][key] +=
        (Number(formState["incinerationEnergyRecovery"]) / 100) *
        (Number(formState["PET"]) *
          Number(dataMatrix["incinerationPETWithEnergyRecovery"][key]) +
          Number(formState["Trilaminate"]) *
            Number(
              dataMatrix["incinerationTrilaminateWithEnergyRecovery"][key]
            ));

      result["End-of-life"][key] +=
        (Number(formState["IncinerationWithoutEnergyRecovery"]) / 100) *
        (Number(formState["PET"]) *
          Number(dataMatrix["incinerationPETWithoutEnergyRecovery"][key]) +
          Number(formState["Trilaminate"]) *
            Number(
              dataMatrix["incinerationTrilaminateWithoutEnergyRecovery"][key]
            ));

      result["End-of-life"][key] +=
        (Number(formState["Landfill"]) / 100) *
        (Number(formState["PET"]) * Number(dataMatrix["landfillPET"][key]) +
          Number(formState["Trilaminate"]) *
            Number(dataMatrix["landfillTrilaminate"][key]));

      result["End-of-life"][key] =
        result["End-of-life"][key] / Number(formState["numUses"]);
    });

    setCurrentChartState({ ...currentChartState, ...result });
  }, [formState]);

  return (
    <>
      <div className="bg-[#f8f8f8] rounded-lg border-2 border-gray-200 shadow-lg shadow-gray-200 px-4 py-[30px] mb-2 relative">
        <h4 className="mb-4 text-[1.8em] font-bold text-gray-700">
          {steps[step].title}
        </h4>
        <p className="mb-8 text-[1.3em] text-gray-500">
          {steps[step].description}
        </p>
        <Separator className="mb-14 h-2 bg-gradient-to-r from-[#295279] via-[#e58f39] to-[#c19ec9]" />
        <div className="flex flex-row gap-30">
          <div className="grid w-full grid-cols-3 gap-10">
            {steps[step].fields?.map((field) => (
              <div
                className="grid w-full max-w-sm content-start align-top gap-1.5"
                key={field.name}
              >
                <Label
                  htmlFor={field.name}
                  className="mb-2 font-semibold text-gray-700 text-sm"
                >
                  {field.label}
                </Label>
                <div className="flex w-full max-w-sm items-center space-x-2">
                  <Input
                    id={field.name}
                    type={field.type}
                    value={formState[field.name]}
                    onChange={(e) => {
                      setFormState({
                        ...formState,
                        [field.name]: Number(e.target.value),
                      });
                    }}
                    placeholder={field.placeholder}
                    className="bg-white focus-visible:ring-[#2374AB] h-10"
                  />
                  <span className="font-bold text-gray-500 text-sm">
                    {field.unit}
                  </span>
                </div>
                <p className="text-gray-600 text-sm">
                  {ReactHtmlParser(field.description)}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
      {Math.max(...Object.values(formState)) > 0 && (
        <Chart currentChartState={currentChartState} />
      )}
    </>
  );
}

export default Calculator;
